services:
  database:
      image: postgres:15
      container_name: database
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=txs-db
        - POSTGRES_USER=${DB_USER}
        - POSTGRES_PASSWORD=${DB_PASSWORD}